"""Initial migration

Revision ID: 928e2eac0eb7
Revises: 
Create Date: 2025-10-05 11:11:37.315639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928e2eac0eb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('process_number', sa.String(length=50), nullable=False),
    sa.Column('court', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('cover_data', sa.JSON(), nullable=True),
    sa.Column('full_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_consultation', sa.DateTime(), nullable=True),
    sa.Column('has_documents', sa.Boolean(), nullable=False),
    sa.Column('documents_downloaded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pdpj'
    )
    op.create_index(op.f('ix_pdpj_processes_process_number'), 'processes', ['process_number'], unique=True, schema='pdpj')
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'READONLY', name='userrole'), nullable=False),
    sa.Column('rate_limit_requests', sa.Integer(), nullable=True),
    sa.Column('rate_limit_window', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pdpj'
    )
    op.create_index(op.f('ix_pdpj_users_api_key'), 'users', ['api_key'], unique=True, schema='pdpj')
    op.create_index(op.f('ix_pdpj_users_username'), 'users', ['username'], unique=True, schema='pdpj')
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('process_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('s3_bucket', sa.String(length=100), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('downloaded', sa.Boolean(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['pdpj.processes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pdpj'
    )
    op.create_index(op.f('ix_pdpj_documents_document_id'), 'documents', ['document_id'], unique=True, schema='pdpj')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdpj_documents_document_id'), table_name='documents', schema='pdpj')
    op.drop_table('documents', schema='pdpj')
    op.drop_index(op.f('ix_pdpj_users_username'), table_name='users', schema='pdpj')
    op.drop_index(op.f('ix_pdpj_users_api_key'), table_name='users', schema='pdpj')
    op.drop_table('users', schema='pdpj')
    op.drop_index(op.f('ix_pdpj_processes_process_number'), table_name='processes', schema='pdpj')
    op.drop_table('processes', schema='pdpj')
    # ### end Alembic commands ###
